apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8fs1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-8fs1@sha256:8532d5565a528a0cae5bad29fd5499c3f9451fc0ca1e7fabf40481e24ebb7b97
        name: my-nodejs
        resources: {}
status: {}
